[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/pair_concentrated",
    "contracts/pair_transmuter",
    #  "contracts/pair_concentrated_inj", TODO: rewrite OB liquidity deployment
    "contracts/pair_astro_xastro",
    "contracts/pair_xyk_sale_tax",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    #  "contracts/cw20_ics20", # contract is being deprecated
    "templates/*",
    "contracts/tokenomics/*",
    "contracts/periphery/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true

[patch.'https://github.com/astroport-fi/astroport-core']
astroport = { path = "packages/astroport" }
