[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    # TODO: do we need to support bluna in 3pool?
    # "contracts/pair_stable_bluna",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "contracts/tokenomics/*",
    "contracts/periphery/*"
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true
