[workspace]
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "contracts/tokenomics/generator",
    "contracts/tokenomics/maker",
    "contracts/tokenomics/staking",
    "contracts/tokenomics/vesting",
    "contracts/tokenomics/xastro_token",
    "contracts/periphery/oracle"
]
exclude = [
    "contracts/tokenomics/generator_proxy_to_mirror", # TODO: update this when mirror migrated to cosmwasm 1.0.0
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
