[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/pair_astro_xastro",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "templates/*",
    "contracts/tokenomics/generator",
    "contracts/tokenomics/maker",
    "contracts/tokenomics/staking",
    "contracts/tokenomics/vesting",
    "contracts/tokenomics/xastro_token",
    "contracts/periphery/*",
]
exclude = [
    "contracts/pair_stable_bluna", # TODO: update this when bluna migrated to cosmwasm 1.0.0
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true
