[package]
name = "astroport-maker"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.1" }
cw2 = { version = "0.15" }
cw20 = { version = "0.15" }
cw-storage-plus = { version = "0.15" }
astroport = { path = "../../../packages/astroport", default-features = false }
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/migrate_to_cosmwasm_1_1_release/terra2" }
thiserror = { version = "1.0" }
cosmwasm-schema = { version = "1.1" }

[dev-dependencies]
astroport-token = {path = "../../token"}
astroport-factory = {path = "../../factory"}
astroport-pair = {path = "../../pair"}
cw-multi-test = "0.15"
astroport-escrow-fee-distributor = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/migrate_to_cosmwasm_1_1_release/terra2" }
