[package]
name = "astroport-maker"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.1"
cw2 = "0.15"
cw20 = "0.15"
cw-storage-plus = "0.15"
schemars = "0.8.1"
astroport = { path = "../../../packages/astroport", default-features = false }
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }
classic-bindings = { version = "0.1.1" }

[dev-dependencies]
cosmwasm-schema = "1.1"
astroport-token = {path = "../../token"}
astroport-factory = {path = "../../factory"}
astroport-pair = {path = "../../pair"}
cw-multi-test = "0.15"
astroport-escrow-fee-distributor = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
