[package]
name = "astroport-maker"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16.2" }
cw2 = { version = "0.8.0" }
cw20 = { version = "0.8.0" }
cw-storage-plus = { version = "0.8.0", features = ["iterator"] }
schemars = "0.8.1"
astroport = { path = "../../../packages/astroport", default-features = false }
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.2" }
astroport-token = {path = "../../token"}
astroport-factory = {path = "../../factory"}
astroport-pair = {path = "../../pair"}
terra-multi-test = {git = "https://github.com/astroport-fi/terra-plus.git", tag = "v0.9.1-terra"}
cosmwasm-bignumber = "2.2.0"
astroport-escrow-fee-distributor = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
