[package]
name = "astroport-vesting"
version = "1.0.0"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw2 = "0.15"
cw20 = "0.15"
cosmwasm-std = "1.1"
cw-storage-plus = "0.15"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport = { path = "../../../packages/astroport", default-features = false }
thiserror = { version = "1.0.20" }
classic-bindings = { version = "0.1.1" }

[dev-dependencies]
cosmwasm-schema = { version = "1.1", default-features = false  }
astroport-token = {path = "../../token"}
classic-test-tube = { version = "0.1.0" }