[package]
name = "astroport-vesting"
version = "1.3.2"
authors = ["Astroport"]
edition = "2021"
description = "Astroport Vesting Contract holds tokens and releases them to the beneficiary over time."
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw2 = { version = "0.15" }
cw20 = { version = "0.15" }
cosmwasm-std = { version = "1.1" }
cw-storage-plus = "0.15"
astroport = { path = "../../../packages/astroport", version = "3" }
thiserror = { version = "1.0" }
cw-utils = "0.15"
cosmwasm-schema = { version = "1.1", default-features = false }

[dev-dependencies]
cw-multi-test = "1.0.0"
astroport-token = { path = "../../token" }
