[package]
name = "astroport-vesting"
version = "1.0.0"
authors = ["Astroport"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw2 = { version = "0.13" }
cw20 = { version = "0.13" }
cosmwasm-std = { version = "1.0" }
cw-storage-plus = {version = "0.13", features = ['iterator']}
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport = { path = "../../../packages/astroport", default-features = false }
thiserror = { version = "1.0" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0", default-features = false  }
cw-multi-test = "0.13"
astroport-token = {path = "../../token"}