[package]
name = "astroport-generator"
version = "2.1.0"
authors = ["Astroport"]
edition = "2021"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.1" }
cw2 = { version = "0.15" }
cw20 = { version = "0.15" }
cw-storage-plus = { version = "0.15" }
schemars = "0.8"
serde = "1.0"
thiserror = { version = "1.0" }
astroport = { path = "../../../packages/astroport"}
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git" }
protobuf = { version = "2", features = ["with-bytes"] }
cosmwasm-schema = { version = "1.1" }

[dev-dependencies]
cw-multi-test = "0.15"
astroport-token = {path = "../../token"}
astroport-vesting = {path = "../vesting"}
astroport-staking = {path = "../staking"}
astroport-generator-proxy-to-mirror = {path = "../generator_proxy_to_mirror"}
astroport-factory = {path = "../../factory"}
astroport-pair = {path = "../../pair"}
astroport-pair-stable = {path = "../../pair_stable"}
astroport-whitelist = { path = "../../whitelist" }
anyhow = "1.0"
generator-controller = { git = "https://github.com/astroport-fi/astroport-governance.git" }
voting-escrow = { git = "https://github.com/astroport-fi/astroport-governance.git" }
voting-escrow-delegation = { git = "https://github.com/astroport-fi/astroport-governance.git" }
astroport-nft = { git = "https://github.com/astroport-fi/astroport-governance.git" }
cw721-base = { version = "0.15", features = ["library"] }

[dev-dependencies.astroport-generator_v120]
git = "https://github.com/astroport-fi/astroport-core"
package = "astroport-generator"
rev = "973aab9419229cb221023066f96b18f2edf75ba8"

[dev-dependencies.astroport-package-generator_v120]
git = "https://github.com/astroport-fi/astroport-core"
package = "astroport"
rev = "973aab9419229cb221023066f96b18f2edf75ba8"
