[package]
name = "astroport-pcl-common"
version = "2.0.1-feeshare-fix"
edition = "2021"
description = "Common package contains math tools and utils for Astroport PCL pairs"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw20 = "1"
thiserror.workspace = true
astroport = { path = "../astroport", version = "4" }
astroport-factory = { path = "../../contracts/factory", version = "1.5", features = ["library"] }
itertools.workspace = true

[dev-dependencies]
anyhow = "1"
