[package]
name = "astroport-liquidity-manager"
version = "1.2.0"
edition = "2021"
description = "Astroport Liquidity Manager contract"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw20 = "1.1"
thiserror.workspace = true
itertools.workspace = true
astroport = { path = "../../../packages/astroport", version = "4" }
cw20-base = { version = "1.1", features = ["library"] }
astroport-pair = { path = "../../pair", features = ["library"], version = "1.5" }
astroport-pair-stable = { path = "../../pair_stable", features = ["library"], version = "3" }
astroport-pair-concentrated = { path = "../../pair_concentrated", features = ["library"], version = "3" }
astroport-pcl-common = { path = "../../../packages/astroport_pcl_common", version = "2.0.1-feeshare-fix" }
astroport-factory = { path = "../../factory", features = ["library"], version = "1" }

[dev-dependencies]
cw-multi-test = "1.0.0"
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
astroport-incentives = { path = "../../tokenomics/incentives", version = "1" }
serde_json = "1.0.96"
anyhow = "1"
derivative = "2.2"
itertools.workspace = true
