[package]
name = "astroport-liquidity-manager"
version = "1.1.0"
edition = "2021"
description = "Astroport Liquidity Manager contract"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
cw-storage-plus = "1.0"
cw20 = "0.15"
thiserror = "1.0"
astroport = { path = "../../../packages/astroport", version = "3" }
cw20-base = { version = "0.15", features = ["library"] }
astroport-pair = { path = "../../pair", features = ["library"], version = "1.5" }
astroport-pair-stable = { path = "../../pair_stable", features = ["library"], version = "3" }
astroport-factory = { path = "../../factory", features = ["library"], version = "1" }

[dev-dependencies]
cw-multi-test = "1.0.0"
astroport-token = { path = "../../token" }
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
astroport-generator = { path = "../../tokenomics/generator" }
astroport-whitelist = { path = "../../whitelist" }
serde_json = "1.0.96"
anyhow = "1"
derivative = "2.2"
itertools = "0.10"
