name: Code coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

#      - name: Upload to codecov.io
#        uses: codecov/codecov-action@v2
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          fail_ci_if_error: true
